[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.81.0",
    "arxiv>=2.4.0",
    "dotenv>=0.9.9",
    "mcp>=1.26.0",
    "nest-asyncio>=1.6.0",
]
