[project]
name = "l3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.81.0",
    "arxiv>=2.4.0",
    "dotenv>=0.9.9",
]
